### ISSUE TITLE
No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by crapthings** [ashleykleynhans/runpod-worker-real-esrgan#3]
what is the working torchvision version?

pip list

torch                   2.2.1
torchvision             0.17.1

```
python .\rp_handler.py
Traceback (most recent call last):
  File "E:\runpod-worker-real-esrgan\rp_handler.py", line 11, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "E:\runpod-worker-real-esrgan\venv\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "E:\runpod-worker-real-esrgan\venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "E:\runpod-worker-real-esrgan\venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "E:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\runpod-worker-real-esrgan\venv\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "E:\runpod-worker-real-esrgan\venv\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
```

**Comment by crapthings** [comment]
0.15 works
